# Setup Python environment via Nixpkgs
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "bash"]

[phases.install]
command = "pip install --no-cache-dir -r requirements.txt"

[phases.start]
command = "bash setup.sh && streamlit run app.py"
