builder="NIXPACKS"
buildCommand="pip install -r requirements.txt"
startCommand="streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true --server.enableCORS false --server.enableXsrfProtection false"
healthcheckPath="/"
healthcheckTimeout="100"
restartPolicyType="ON_FAILURE"
restartPolicyMaxRetries="10"
aptPkgs="['libpq-dev', 'python3-dev']"